In [1]:
!pip install numpy


In [2]:
import numpy as np



In [8]:
### how to create an array
## creating 1d array
one_d_arr=np.array([1,2,3,4,5])
print(one_d_arr)
print(type(one_d_arr))
##<class'numpy.ndarray'> means it is an array of n dimensions

print(one_d_arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
two_d_arr=np.array([1,2,3,4,5])
two_d_arr.reshape(1,5) ##--> this change the state of one dimensional array to 2 dimensional array
## the output has 2 square brackets which means that it is 2 dimensional array

array([[1, 2, 3, 4, 5]])

In [11]:
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1)
print(arr1.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [ ]:
##arange function for numpy
np.arange(0,10,2).reshape(5,1)###--> (0,10,2)-> it means rnage from 0-10 and a space of 2 digit in between
###reshape(5,1)--> it means that 5 rows and 1 column



array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
### np.one function of numpy

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## ti create identity matrix we use eye function of numpy
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr1=np.array([[1,2,3],[2,3,4]])
print("Array",arr1)
print(arr1.shape)
print(arr1.ndim)#-->ndim stands for n dimensions --> it prints the dimensions of array
print(arr1.size)#--> it prints how many elements are there in the array
print(arr1.dtype)#--> it prints the data type of the array
print(arr1.itemsize)#--> the size of the array in bytes


Array [[1 2 3]
 [2 3 4]]
(2, 3)
2
6
int32
4


In [19]:
##Vectorized functionality 
vectors=np.array([1,2,3,4])
vectors1=np.array([5,3,5,6])

## every thing is done index wise 
## elements wise addition
print(vectors+vectors1)

## elements wise subtraction
print(vectors-vectors1)

## elements wise multiplication
print(vectors*vectors1)

## elements wise division
print(vectors/vectors1)

[ 6  5  8 10]
[-4 -1 -2 -2]
[ 5  6 15 24]
[0.2        0.66666667 0.6        0.66666667]


In [22]:
##universal functions

## this is also done elements wise
arr1=np.array([1,2,3,4])
##sqrt 
print(np.sqrt(arr1))
##sin
print(np.sin(arr1))
##log
print(np.log(arr1))
##exponential
print(np.exp(arr1))



[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
##slicing index
slicing_index=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",slicing_index)
print("Array Dimension?:",slicing_index.ndim)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array Dimension?: 2


In [28]:
## to access an element will do index slicing -- not mango slice but real slicing
slicing_index[0][0]

1

In [29]:
slicing_index[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
slicing_index[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [32]:
slicing_index[1:2,1:]

array([[6, 7, 8]])

In [34]:
## wE CAN ALSO MODIFY THE ELEMENTS
slicing_index[2,2]=1214
print(slicing_index)

[[   1    2    3    4]
 [   5    6    7    8]
 [   9   10 1214   12]]


In [35]:
##also we can change whole elments series 
slicing_index[1:,]=1214
print(slicing_index)

[[   1    2    3    4]
 [1214 1214 1214 1214]
 [1214 1214 1214 1214]]


In [38]:
##lets calculate normalizagtion of data 
given_data=np.array([1,2,3,5,4])
mean=np.mean(given_data)
print("Mean of the given_data:",mean)
std_dev=np.std(given_data)
print("Standard Deviation of the given_data:",std_dev)

normalized_data=(given_data-mean)/std_dev

print("Normalized data:",normalized_data)

Mean of the given_data: 3.0
Standard Deviation of the given_data: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          1.41421356  0.70710678]


In [ ]:
##to calculate the mean,median,mode of the data
data=np.array([1,2,3,4,5])
##Mean of the data
mean=np.mean(data)
print("Mean of the data:",mean)
##Standard deviation of the data
std_dev=np.std(data)
print("Standard Deviation of the data:",std_dev)
##meadian of the data
median_data=np.median(data)
print("Medain of the data:",median_data)
##variance of the data
variation_Data=np.var(data)
print("Variance of the data:",variation_Data)

Mean of the data: 3.0
Standard Deviation of the data: 1.4142135623730951
Medain of the data: 3.0
Variation of the data: 2.0


In [43]:
##Logical operation
data=np.array([1,2,3,4,5,6,7,8])
print(data>5)
print(data[data>5])
print(data[(data>5) & (data<8)])##--> cannot use 'and' operator in this we need to use '&' for logival opertion in numpy

[False False False False False  True  True  True]
[6 7 8]
[6 7]
